name: d8example
recipe: drupal8
config:
  webroot: projeto/web
  drush: 8.3.2
  php: 7.3
services:
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  gulp:
    service: node
  node:
    service: node
  npm:
    service: node